### ISSUE TITLE
Stop using CMD with Windows

### ISSUE THREAD

**Issue by ghost** [pkg/browser#16]
The current Windows incarnation is brittle:

https://github.com/pkg/browser/blob/0a3d74bf9ce488f035cf5bc36f753a711bc74334/browser_windows.go#L9-L12

it survives ampersands, but not other characters:

~~~go
package main
import "github.com/pkg/browser"
func main() {
   browser.OpenURL("http://example.com?aa bb&cc")
}
~~~

better would be to call RunDLL32, no replacer needed. Examples:

~~~sh
rundll32 url,OpenURL "http://example.com?aa bb&cc"
rundll32 url,FileProtocolHandler "http://example.com?aa bb&cc"
~~~

https://github.com/skratchdot/open-golang/blob/master/open/exec_windows.go

Or call browser directly via the BROWSER environment variable. This is what
Python does:

~~~py
import webbrowser
webbrowser.open('http://example.com?aa bb&cc')
~~~

https://github.com/python/cpython/blob/master/Lib/webbrowser.py

Or better still would be to call `ShellExecuteW` on Windows:

https://docs.microsoft.com/windows/win32/api/shellapi/nf-shellapi-shellexecutew

This is what D does:

~~~d
import std.process;
void main() {
   browse("http://example.com?aa bb&cc");
}
~~~

https://github.com/dlang/phobos/blob/master/std/process.d

and Nim:

~~~nim
import browsers
openDefaultBrowser("http://example.com?aa bb&cc")
~~~

https://github.com/nim-lang/Nim/blob/devel/lib/pure/browsers.nim

**Comment by luna-duclos** [comment]
PRs definately welcome for this, might get to it myself eventually, but no guarantees :)

**Comment by 89z** [comment]
https://github.com/pkg/browser/pull/27
