### ISSUE TITLE
Package should not log anything by default

### ISSUE THREAD

**Issue by Trey2k** [pkg/browser#18]
Logging things in packages is not the Go way of doing things. the package should never log anything or at least have a way to disable it. IE i get these logs when I use the package on Debian
"Icon theme "gnome" not found.
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found."

**Comment by davecheney** [comment]
I think these lines come from the process forked by this package.
