### ISSUE TITLE
Add support for freebsd OS

### ISSUE THREAD

**Issue by gllb** [pkg/browser#20]
Freebsd is unsupported, it need to run same openBrowser command than OpenBSD.

**Comment by davecheney** [comment]
Happy to take a PR

**Comment by gllb** [comment]
there you go : https://github.com/pkg/browser/pull/21

**Comment by gllb** [comment]
Sorry about the regression ... I think it's the space that I add on build constraint line in browser_unsupported.go which cause issue. 
I'll test it to be sure.
