### ISSUE TITLE
browser_unsupported error with build

### ISSUE THREAD

**Issue by chris93111** [pkg/browser#37]
Hi 

I try to build with solaris but i have this error
../../pkg/mod/github.com/pkg/browser@v0.0.0-20210706143420-7d21f8c997e2/browser_unsupported.go:7:2: imported and not used: "os/exec"

**Comment by davecheney** [comment]
Sorry, there is no support for Solaris. If you want to send a PR, I can’t imagine it would be different from a Linux or bad derivative, that would be ace.

**Comment by chris93111** [comment]
Hi @davecheney yes i know but i build for many os, and with this error i inderstand browser_unsupported.go is used for solaris and contain import not used

**Comment by chris93111** [comment]
fixes with https://github.com/pkg/browser/pull/38
