### ISSUE TITLE
browser.OpenURL does not work with windows GUI

### ISSUE THREAD

**Issue by jimbojetlag** [pkg/browser#6]
When compiled with `-ldflags "-H windowsgui"`, `browser.OpenURL` does not work at all.

**Comment by davecheney** [comment]
I'm sorry, I don't use Windows so I don't have a way to test o fix this. If you can fix it, please send a PR

**Comment by jimbojetlag** [comment]
Thanks @davecheney . The error seems to be `The handle is invalid` which simply means there is no console to run the `start` command to open the browser.

The only way I could so far find is to attach or allocate a console, and then open the url, as described in http://stackoverflow.com/a/23744350 . 

This is not the ideal case.

**Comment by henvic** [comment]
@davecheney can you please take a look at #8? Thanks!

**Comment by luna-duclos** [comment]
WSL support should now work via forking out to x-www-browser or www-browser, more OS specific commands (but ideally not WSL specific) can be added if needed.
